services:
  - type: web
    name: flipflop-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.api:app --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
